SCALE Job started on Mon 23/01/2023 00:38:33
With Host name node60
working directory /tmp/scale.ondrejch.366060
and process id 366060.
Input file named /home/ondrejch/scale/rt/HW2-3/2_3
and output file named /home/ondrejch/scale/rt/HW2-3/2_3.out
##########################################################
***Created 6 infinite homogeneous cells from unreferenced mixtures.
***Warning: Nuclide 8018 is missing cross sections. Introducing zero cross sections.
>>> Loading SCALE Standard Composition Library from /opt/scale6.2_data/scale.rev39.sclib
>>> Loading CE library /opt/scale6.2_data/ce_v7.1_endf.xml
