SCALE Job started on Mon 23/01/2023 01:37:33
With Host name node18
working directory /tmp/scale.ondrejch.2024904
and process id 2024904.
Input file named /home/ondrejch/scale/rt/HW2-4/temp0430/2_4
and output file named /home/ondrejch/scale/rt/HW2-4/temp0430/2_4.out
##########################################################
***Created 1 infinite homogeneous cells from unreferenced mixtures.
***Warning: Nuclide 8018 is missing cross sections. Introducing zero cross sections.
>>> Loading SCALE Standard Composition Library from /opt/scale6.2_data/scale.rev39.sclib
>>> Loading CE library /opt/scale6.2_data/ce_v7.1_endf.xml
