SCALE Job started on Mon 23/01/2023 01:35:45
With Host name node69
working directory /tmp/scale.ondrejch.953331
and process id 953331.
Input file named /home/ondrejch/scale/rt/HW2-4/enr060/2_4
and output file named /home/ondrejch/scale/rt/HW2-4/enr060/2_4.out
##########################################################
***Created 1 infinite homogeneous cells from unreferenced mixtures.
***Warning: Nuclide 8018 is missing cross sections. Introducing zero cross sections.
>>> Loading SCALE Standard Composition Library from /opt/scale6.2_data/scale.rev39.sclib
>>> Loading CE library /opt/scale6.2_data/ce_v7.1_endf.xml
