SCALE Job started on Wed 25/01/2023 00:40:18
With Host name necluster
working directory /tmp/scale.ondrejch.680755
and process id 680755.
Input file named /home/ondrejch/scale/rt/ME388D_S23_HW2/HW2-4/fuel0.170/2_4
and output file named /home/ondrejch/scale/rt/ME388D_S23_HW2/HW2-4/fuel0.170/2_4.out
##########################################################
***Created 1 infinite homogeneous cells from unreferenced mixtures.
***Warning: Nuclide 8018 is missing cross sections. Introducing zero cross sections.
>>> Loading SCALE Standard Composition Library from /opt/scale6.2_data/scale.rev39.sclib
>>> Loading CE library /opt/scale6.2_data/ce_v7.1_endf.xml
